package com.dao;

import com.model.OnlineRecord;
import com.model.OnlineRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface OnlineRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    long countByExample(OnlineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int deleteByExample(OnlineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Delete({
        "delete from online_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Insert({
        "insert into online_record (user_id, online_time, ",
        "online_loc)",
        "values (#{userId,jdbcType=INTEGER}, #{onlineTime,jdbcType=DATE}, ",
        "#{onlineLoc,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(OnlineRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int insertSelective(OnlineRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    List<OnlineRecord> selectByExample(OnlineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Select({
        "select",
        "id, user_id, online_time, online_loc",
        "from online_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.dao.OnlineRecordMapper.BaseResultMap")
    OnlineRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int updateByExampleSelective(@Param("record") OnlineRecord record, @Param("example") OnlineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int updateByExample(@Param("record") OnlineRecord record, @Param("example") OnlineRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int updateByPrimaryKeySelective(OnlineRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Update({
        "update online_record",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "online_time = #{onlineTime,jdbcType=DATE},",
          "online_loc = #{onlineLoc,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OnlineRecord record);
}