package com.dao;

import com.model.Restaurants;
import com.model.RestaurantsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RestaurantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    long countByExample(RestaurantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    int deleteByExample(RestaurantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    int insert(Restaurants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    int insertSelective(Restaurants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    List<Restaurants> selectByExample(RestaurantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    Restaurants selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    int updateByExampleSelective(@Param("record") Restaurants record, @Param("example") RestaurantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    int updateByExample(@Param("record") Restaurants record, @Param("example") RestaurantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    int updateByPrimaryKeySelective(Restaurants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurants
     *
     * @mbg.generated Sat Mar 10 22:37:40 HKT 2018
     */
    int updateByPrimaryKey(Restaurants record);
}