package com.dao;

import com.model.UserRestaurantHistory;
import com.model.UserRestaurantHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface UserRestaurantHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    long countByExample(UserRestaurantHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int deleteByExample(UserRestaurantHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Delete({
        "delete from user_restaurant_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Insert({
        "insert into user_restaurant_history (user_id, restaurant_id)",
        "values (#{userId,jdbcType=INTEGER}, #{restaurantId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(UserRestaurantHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int insertSelective(UserRestaurantHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    List<UserRestaurantHistory> selectByExample(UserRestaurantHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Select({
        "select",
        "id, user_id, restaurant_id",
        "from user_restaurant_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.dao.UserRestaurantHistoryMapper.BaseResultMap")
    UserRestaurantHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int updateByExampleSelective(@Param("record") UserRestaurantHistory record, @Param("example") UserRestaurantHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int updateByExample(@Param("record") UserRestaurantHistory record, @Param("example") UserRestaurantHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int updateByPrimaryKeySelective(UserRestaurantHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Update({
        "update user_restaurant_history",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "restaurant_id = #{restaurantId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserRestaurantHistory record);
}