package com.dao;

import com.model.UserOrderHistory;
import com.model.UserOrderHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface UserOrderHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    long countByExample(UserOrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int deleteByExample(UserOrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Delete({
        "delete from user_order_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Insert({
        "insert into user_order_history (user_id, order_id)",
        "values (#{userId,jdbcType=INTEGER}, #{orderId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(UserOrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int insertSelective(UserOrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    List<UserOrderHistory> selectByExample(UserOrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Select({
        "select",
        "id, user_id, order_id",
        "from user_order_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.dao.UserOrderHistoryMapper.BaseResultMap")
    UserOrderHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int updateByExampleSelective(@Param("record") UserOrderHistory record, @Param("example") UserOrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int updateByExample(@Param("record") UserOrderHistory record, @Param("example") UserOrderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    int updateByPrimaryKeySelective(UserOrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    @Update({
        "update user_order_history",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "order_id = #{orderId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserOrderHistory record);
}