package com.model;

import java.util.Date;

public class OnlineRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_record.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_record.user_id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_record.online_time
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Date onlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_record.online_loc
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private String onlineLoc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_record
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public OnlineRecord(Integer id, Integer userId, Date onlineTime, String onlineLoc) {
        this.id = id;
        this.userId = userId;
        this.onlineTime = onlineTime;
        this.onlineLoc = onlineLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_record.id
     *
     * @return the value of online_record.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_record.user_id
     *
     * @return the value of online_record.user_id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_record.online_time
     *
     * @return the value of online_record.online_time
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Date getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_record.online_loc
     *
     * @return the value of online_record.online_loc
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public String getOnlineLoc() {
        return onlineLoc;
    }
}