package com.model;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.userA
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer usera;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.userB
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer userb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_date
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.finish_date
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Date finishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.restaurant_id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer restaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.reason
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Boolean reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Orders(Integer id, Integer usera, Integer userb, Date createDate, Date finishDate, Integer restaurantId, Boolean reason) {
        this.id = id;
        this.usera = usera;
        this.userb = userb;
        this.createDate = createDate;
        this.finishDate = finishDate;
        this.restaurantId = restaurantId;
        this.reason = reason;
    }
    public Orders(){

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.userA
     *
     * @return the value of orders.userA
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getUsera() {
        return usera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.userB
     *
     * @return the value of orders.userB
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getUserb() {
        return userb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_date
     *
     * @return the value of orders.create_date
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.finish_date
     *
     * @return the value of orders.finish_date
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.restaurant_id
     *
     * @return the value of orders.restaurant_id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.reason
     *
     * @return the value of orders.reason
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Boolean getReason() {
        return reason;
    }
}