package com.model;

import java.util.Date;

public class RecordOffline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_offline.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_offline.offline_time
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Date offlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_offline.offline_loc
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private String offlineLoc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_offline
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public RecordOffline(Integer id, Date offlineTime, String offlineLoc) {
        this.id = id;
        this.offlineTime = offlineTime;
        this.offlineLoc = offlineLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_offline.id
     *
     * @return the value of record_offline.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_offline.offline_time
     *
     * @return the value of record_offline.offline_time
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Date getOfflineTime() {
        return offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_offline.offline_loc
     *
     * @return the value of record_offline.offline_loc
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public String getOfflineLoc() {
        return offlineLoc;
    }
}