package com.model;

public class Restaurant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.id
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.name
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public Restaurant(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.id
     *
     * @return the value of restaurant.id
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.name
     *
     * @return the value of restaurant.name
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public String getName() {
        return name;
    }
}