package com.model;

import java.util.ArrayList;
import java.util.Date;

public class Restaurant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.name
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.create_date
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.is_deleted
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Restaurant(Integer id, String name, Date createDate, Boolean isDeleted) {
        this.id = id;
        this.name = name;
        this.createDate = createDate;
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.id
     *
     * @return the value of restaurant.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.name
     *
     * @return the value of restaurant.name
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.create_date
     *
     * @return the value of restaurant.create_date
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.is_deleted
     *
     * @return the value of restaurant.is_deleted
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    private Integer uid;
    private Integer sharer_num;
    private ArrayList<String> sharer_ids;
    private Location location;
    private ArrayList<String> tags;
    public Restaurant(int uid, String name, int sharer_num, ArrayList<String> sharer_ids,
                      Location location, ArrayList<String> tags){
        this.uid = uid;
        this.name = name;
        this.sharer_num = sharer_num;
        this.sharer_ids = sharer_ids;
        this.location = location;
        this.tags = tags;
    }
    public int getUid(){
        return uid;
    }
    public int getShare_num(){
        return sharer_num;
    }
    public ArrayList<String> getShare_ids(){
        return sharer_ids;
    }
    public Location getLocation(){
        return location;
    }
    public ArrayList<String> getTags(){
        return tags;
    }

}