package com.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.type
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sessionId
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private String sessionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public User(Integer id, String name, String password, String type, String sessionid) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.type = type;
        this.sessionid = sessionid;
    }
    public User(String name, String password, String type, String sessionid) {
        this.name = name;
        this.password = password;
        this.type = type;
        this.sessionid = sessionid;
    }
    public User(String name, String password, String type) {
        this.name = name;
        this.password = password;
        this.type = type;
    }
    public User(String name, String password) {
        this.name = name;
        this.password = password;
    }
    public void setSessionid(String sessionid){
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sessionId
     *
     * @return the value of user.sessionId
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public String getSessionid() {
        return sessionid;
    }
}