package com.model;

public class UserRestaurantHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_restaurant_history.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_restaurant_history.user_id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_restaurant_history.restaurant_id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    private Integer restaurantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public UserRestaurantHistory(Integer id, Integer userId, Integer restaurantId) {
        this.id = id;
        this.userId = userId;
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_restaurant_history.id
     *
     * @return the value of user_restaurant_history.id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_restaurant_history.user_id
     *
     * @return the value of user_restaurant_history.user_id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_restaurant_history.restaurant_id
     *
     * @return the value of user_restaurant_history.restaurant_id
     *
     * @mbg.generated Tue Dec 05 21:16:15 HKT 2017
     */
    public Integer getRestaurantId() {
        return restaurantId;
    }
}