package com.model;

public class UserOrderHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_history.id
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_history.uid
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_history.oid
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    private Integer oid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_history
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public UserOrderHistory(Integer id, Integer uid, Integer oid) {
        this.id = id;
        this.uid = uid;
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_history.id
     *
     * @return the value of user_order_history.id
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_history.uid
     *
     * @return the value of user_order_history.uid
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_history.oid
     *
     * @return the value of user_order_history.oid
     *
     * @mbg.generated Mon Mar 12 17:09:41 HKT 2018
     */
    public Integer getOid() {
        return oid;
    }
}