package com.model;

public class UserRestaurantHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_restaurant_history.id
     *
     * @mbg.generated Sat Mar 10 23:22:19 HKT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_restaurant_history.uid
     *
     * @mbg.generated Sat Mar 10 23:22:19 HKT 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_restaurant_history.rid
     *
     * @mbg.generated Sat Mar 10 23:22:19 HKT 2018
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_restaurant_history
     *
     * @mbg.generated Sat Mar 10 23:22:19 HKT 2018
     */
    public UserRestaurantHistory(Integer id, Integer uid, Integer rid) {
        this.id = id;
        this.uid = uid;
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_restaurant_history.id
     *
     * @return the value of user_restaurant_history.id
     *
     * @mbg.generated Sat Mar 10 23:22:19 HKT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_restaurant_history.uid
     *
     * @return the value of user_restaurant_history.uid
     *
     * @mbg.generated Sat Mar 10 23:22:19 HKT 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_restaurant_history.rid
     *
     * @return the value of user_restaurant_history.rid
     *
     * @mbg.generated Sat Mar 10 23:22:19 HKT 2018
     */
    public Integer getRid() {
        return rid;
    }
}